/*
  firebird-schema.sql — DDL для InspectionList в Firebird 3.0+
  Запустить один раз через FlameRobin, isql или DBeaver.

  Порядок выполнения:
    1. Создать пустую базу данных InspectionList.fdb
    2. Подключиться и выполнить этот скрипт
    3. Запустить: node server/migrate-to-firebird.js
*/

SET NAMES UTF8;
SET SQL DIALECT 3;

/* ═══════════════════════════════════════════════════════════════
  ПОСЛЕДОВАТЕЛЬНОСТИ (автоинкрементные ID)
═══════════════════════════════════════════════════════════════ */

CREATE SEQUENCE GEN_SHEETS_ID;
CREATE SEQUENCE GEN_DEFECTS_ID;

/* ═══════════════════════════════════════════════════════════════
  СПРАВОЧНИКИ (заполняются один раз через migrate-to-firebird.js)
═══════════════════════════════════════════════════════════════ */

CREATE TABLE FILIALS (
  ID   INTEGER      NOT NULL,
  NAME VARCHAR(200) CHARACTER SET UTF8 NOT NULL,
  CONSTRAINT PK_FILIALS PRIMARY KEY (ID)
);

CREATE TABLE VOLTAGES (
  ID        INTEGER      NOT NULL,
  NAME      VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
  FILIAL_ID INTEGER,
  CONSTRAINT PK_VOLTAGES    PRIMARY KEY (ID),
  CONSTRAINT FK_VOLT_FILIAL FOREIGN KEY (FILIAL_ID) REFERENCES FILIALS(ID)
);

CREATE TABLE LINES (
  ID                  INTEGER        NOT NULL,
  NAME                VARCHAR(400)   CHARACTER SET UTF8 NOT NULL,
  VOLTAGE_ID          INTEGER,
  FILIAL_ID           INTEGER,
  POLE_RANGE          VARCHAR(50)    CHARACTER SET UTF8,
  POLE_START          INTEGER,
  POLE_END            INTEGER,
  POLE_COUNT          INTEGER,
  YEAR_BUILT          INTEGER,
  YEAR_LAST_OVERHAUL  INTEGER,
  LENGTH_KM           NUMERIC(10,2),
  POLE_TYPE           VARCHAR(200)   CHARACTER SET UTF8,
  WIRE_TYPE           VARCHAR(100)   CHARACTER SET UTF8,
  NOTES               VARCHAR(2000)  CHARACTER SET UTF8,
  CONSTRAINT PK_LINES         PRIMARY KEY (ID),
  CONSTRAINT FK_LINES_VOLTAGE FOREIGN KEY (VOLTAGE_ID) REFERENCES VOLTAGES(ID)
);

CREATE INDEX IDX_LINES_VOLTAGE ON LINES (VOLTAGE_ID);
CREATE INDEX IDX_LINES_FILIAL  ON LINES (FILIAL_ID);

CREATE TABLE ELEMENTS (
  ID   INTEGER      NOT NULL,
  NAME VARCHAR(400) CHARACTER SET UTF8 NOT NULL,
  CONSTRAINT PK_ELEMENTS PRIMARY KEY (ID)
);

CREATE TABLE DEFECT_TYPES (
  ID         INTEGER      NOT NULL,
  NAME       VARCHAR(600) CHARACTER SET UTF8 NOT NULL,
  SEVERITY   VARCHAR(20)  CHARACTER SET UTF8,
  ELEMENT_ID INTEGER,
  CONSTRAINT PK_DEFECT_TYPES PRIMARY KEY (ID),
  CONSTRAINT FK_DT_ELEMENT   FOREIGN KEY (ELEMENT_ID) REFERENCES ELEMENTS(ID)
);

CREATE INDEX IDX_DT_ELEMENT ON DEFECT_TYPES (ELEMENT_ID);

CREATE TABLE PHASES (
  ID   INTEGER     NOT NULL,
  NAME VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  CONSTRAINT PK_PHASES PRIMARY KEY (ID)
);

CREATE TABLE PHASE_ELEMENT_IDS (
  PHASE_ID   INTEGER NOT NULL,
  ELEMENT_ID INTEGER NOT NULL,
  CONSTRAINT PK_PHASE_ELEM PRIMARY KEY (PHASE_ID, ELEMENT_ID),
  CONSTRAINT FK_PE_PHASE   FOREIGN KEY (PHASE_ID)   REFERENCES PHASES(ID),
  CONSTRAINT FK_PE_ELEMENT FOREIGN KEY (ELEMENT_ID) REFERENCES ELEMENTS(ID)
);

/* filialId → разрешённые voltageId */
CREATE TABLE FILIAL_VOLTAGE_FILTER (
  FILIAL_ID  INTEGER NOT NULL,
  VOLTAGE_ID INTEGER NOT NULL,
  CONSTRAINT PK_FVF        PRIMARY KEY (FILIAL_ID, VOLTAGE_ID),
  CONSTRAINT FK_FVF_FILIAL  FOREIGN KEY (FILIAL_ID)  REFERENCES FILIALS(ID),
  CONSTRAINT FK_FVF_VOLTAGE FOREIGN KEY (VOLTAGE_ID) REFERENCES VOLTAGES(ID)
);

/* ═══════════════════════════════════════════════════════════════
  ПОЛЬЗОВАТЕЛИ
═══════════════════════════════════════════════════════════════ */

CREATE TABLE USERS (
  ID           VARCHAR(50)  CHARACTER SET UTF8  NOT NULL,
  USERNAME     VARCHAR(100) CHARACTER SET UTF8  NOT NULL,
  PASSWORD     VARCHAR(200) CHARACTER SET NONE  NOT NULL,
  DISPLAY_NAME VARCHAR(200) CHARACTER SET UTF8,
  ROLE         VARCHAR(50)  CHARACTER SET UTF8  DEFAULT 'viewer',
  FILIAL_ID    INTEGER,
  CONSTRAINT PK_USERS          PRIMARY KEY (ID),
  CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
  CONSTRAINT FK_USERS_FILIAL   FOREIGN KEY (FILIAL_ID) REFERENCES FILIALS(ID)
);

/* Разрешённые линии для пользователя (role=master) */
CREATE TABLE USER_ALLOWED_LINES (
  USER_ID VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  LINE_ID INTEGER                         NOT NULL,
  CONSTRAINT PK_UAL      PRIMARY KEY (USER_ID, LINE_ID),
  CONSTRAINT FK_UAL_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_UAL_LINE FOREIGN KEY (LINE_ID) REFERENCES LINES(ID)
);

/* Разрешённые напряжения для пользователя (role=engineer) */
CREATE TABLE USER_ALLOWED_VOLTAGES (
  USER_ID    VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  VOLTAGE_ID INTEGER                         NOT NULL,
  CONSTRAINT PK_UAV         PRIMARY KEY (USER_ID, VOLTAGE_ID),
  CONSTRAINT FK_UAV_USER    FOREIGN KEY (USER_ID)    REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_UAV_VOLTAGE FOREIGN KEY (VOLTAGE_ID) REFERENCES VOLTAGES(ID)
);

/* ═══════════════════════════════════════════════════════════════
  ЛИСТКИ ОСМОТРА
═══════════════════════════════════════════════════════════════ */

CREATE TABLE INSPECTION_SHEETS (
  ID           INTEGER      NOT NULL,
  FILIAL_ID    INTEGER,
  VOLTAGE_ID   INTEGER,
  LINE_ID      INTEGER,
  CREATED_BY   VARCHAR(200) CHARACTER SET UTF8,
  CREATED_DATE DATE,
  STATUS       VARCHAR(50)  CHARACTER SET UTF8 DEFAULT 'active',
  NOTES        VARCHAR(2000) CHARACTER SET UTF8,
  CONSTRAINT PK_SHEETS         PRIMARY KEY (ID),
  CONSTRAINT FK_SHEETS_FILIAL  FOREIGN KEY (FILIAL_ID)  REFERENCES FILIALS(ID),
  CONSTRAINT FK_SHEETS_VOLTAGE FOREIGN KEY (VOLTAGE_ID) REFERENCES VOLTAGES(ID),
  CONSTRAINT FK_SHEETS_LINE    FOREIGN KEY (LINE_ID)    REFERENCES LINES(ID)
);

CREATE INDEX IDX_SHEETS_LINE    ON INSPECTION_SHEETS (LINE_ID);
CREATE INDEX IDX_SHEETS_DATE    ON INSPECTION_SHEETS (CREATED_DATE);
CREATE INDEX IDX_SHEETS_FILIAL  ON INSPECTION_SHEETS (FILIAL_ID);
CREATE INDEX IDX_SHEETS_STATUS  ON INSPECTION_SHEETS (STATUS);

/* Уникальность: одна линия — одна дата */
CREATE UNIQUE INDEX UQ_SHEETS_LINE_DATE ON INSPECTION_SHEETS (LINE_ID, CREATED_DATE);

/* ═══════════════════════════════════════════════════════════════
  ЗАПИСИ О ДЕФЕКТАХ
═══════════════════════════════════════════════════════════════ */

CREATE TABLE DEFECT_RECORDS (
  ID                  INTEGER       NOT NULL,
  SHEET_ID            INTEGER,
  LINE_ID             INTEGER,
  POLE_NUMBER         INTEGER,
  DEFECT_ID           INTEGER,
  PHASE_ID            INTEGER,
  ELEMENT_ID          INTEGER,
  DATE_FOUND          DATE,
  INSPECTOR_FIND      VARCHAR(200)  CHARACTER SET UTF8,
  IS_FIXED            SMALLINT      DEFAULT 0,
  DATE_FIXED          DATE,
  INSPECTOR_FIX       VARCHAR(200)  CHARACTER SET UTF8,
  INSULATOR_COUNT     INTEGER,
  SPAN_RANGE          VARCHAR(50)   CHARACTER SET UTF8,
  NOTES               VARCHAR(2000) CHARACTER SET UTF8,
  STATUS              VARCHAR(50)   CHARACTER SET UTF8,
  MASTER_CONCLUSION   VARCHAR(4000) CHARACTER SET UTF8,
  RESOLUTION_DEADLINE DATE,
  MASTER_NAME         VARCHAR(200)  CHARACTER SET UTF8,
  FIX_WORK_VOLUME     VARCHAR(2000) CHARACTER SET UTF8,
  CONSTRAINT PK_DEFECTS      PRIMARY KEY (ID),
  CONSTRAINT FK_DEF_SHEET    FOREIGN KEY (SHEET_ID)   REFERENCES INSPECTION_SHEETS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_DEF_LINE     FOREIGN KEY (LINE_ID)    REFERENCES LINES(ID),
  CONSTRAINT FK_DEF_TYPE     FOREIGN KEY (DEFECT_ID)  REFERENCES DEFECT_TYPES(ID),
  CONSTRAINT FK_DEF_PHASE    FOREIGN KEY (PHASE_ID)   REFERENCES PHASES(ID),
  CONSTRAINT FK_DEF_ELEMENT  FOREIGN KEY (ELEMENT_ID) REFERENCES ELEMENTS(ID)
);

CREATE INDEX IDX_DEF_SHEET    ON DEFECT_RECORDS (SHEET_ID);
CREATE INDEX IDX_DEF_LINE     ON DEFECT_RECORDS (LINE_ID);
CREATE INDEX IDX_DEF_FIXED    ON DEFECT_RECORDS (IS_FIXED);
CREATE INDEX IDX_DEF_POLE     ON DEFECT_RECORDS (POLE_NUMBER);
CREATE INDEX IDX_DEF_DATE     ON DEFECT_RECORDS (DATE_FOUND);
CREATE INDEX IDX_DEF_DEFTYPE  ON DEFECT_RECORDS (DEFECT_ID);

COMMIT;
